#!/bin/bash
# generate_concat_ddl.sh — Concatenate all DDL files into a single deployable SQL file.
#
# Reads ddl/deploy_order.txt, applies variable substitution from ddl/variables.env,
# and writes the result to ddl/all_tables.sql.
#
# Usage:
#   ./scripts/generate_concat_ddl.sh
#
# Output:
#   ddl/all_tables.sql — single SQL file with all 100 tables + 15 views,
#   ready for: bq query --use_legacy_sql=false --dry_run < ddl/all_tables.sql

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_ORDER="$PROJECT_ROOT/ddl/deploy_order.txt"
VARIABLES_ENV="$PROJECT_ROOT/ddl/variables.env"
OUTPUT_FILE="$PROJECT_ROOT/ddl/all_tables.sql"

# Validate inputs exist
if [ ! -f "$DEPLOY_ORDER" ]; then
    echo "ERROR: deploy_order.txt not found at $DEPLOY_ORDER" >&2
    exit 1
fi
if [ ! -f "$VARIABLES_ENV" ]; then
    echo "ERROR: variables.env not found at $VARIABLES_ENV" >&2
    exit 1
fi

# Source variables for envsubst
set -a
# shellcheck source=../ddl/variables.env
. "$VARIABLES_ENV"
set +a

# Build the list of variable names for envsubst (restrict substitution to known vars only)
ENVSUBST_VARS='${PROJECT_US}${PROJECT_EU}${DATASET_RAW}${DATASET_STAGING}${DATASET_RETAIL}${DATASET_REGIONAL}${LOCATION_EU}'

# Counters
TABLE_COUNT=0
VIEW_COUNT=0
FILE_COUNT=0
CURRENT_DATASET=""

# Write header
cat > "$OUTPUT_FILE" <<'EOF'
-- ============================================================================
-- BigQuery DDL: All Tables and Views (Auto-Generated)
-- ============================================================================
-- Generated by: scripts/generate_concat_ddl.sh
-- Source: ddl/deploy_order.txt + ddl/variables.env
--
-- This file contains all 100 CREATE TABLE and 15 CREATE OR REPLACE VIEW
-- statements in dependency-correct deployment order.
--
-- Usage:
--   bq query --use_legacy_sql=false --dry_run < ddl/all_tables.sql
--   bq query --use_legacy_sql=false < ddl/all_tables.sql
-- ============================================================================

EOF

# Process each file in deploy order
while IFS= read -r line || [ -n "$line" ]; do
    # Skip comments and blank lines
    case "$line" in
        '#'*) continue ;;
        '')   continue ;;
    esac

    # Trim whitespace
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [ -z "$line" ] && continue

    SQL_FILE="$PROJECT_ROOT/ddl/$line"

    if [ ! -f "$SQL_FILE" ]; then
        echo "WARNING: File not found: $SQL_FILE" >&2
        continue
    fi

    # Detect dataset change for section headers
    NEW_DATASET="$(echo "$line" | cut -d'/' -f1)"
    if [ "$NEW_DATASET" != "$CURRENT_DATASET" ]; then
        CURRENT_DATASET="$NEW_DATASET"
        case "$CURRENT_DATASET" in
            raw)          SECTION_LABEL="RAW dataset — ${PROJECT_US}.${DATASET_RAW}" ;;
            staging)      SECTION_LABEL="STAGING dataset — ${PROJECT_US}.${DATASET_STAGING}" ;;
            retail)       SECTION_LABEL="RETAIL dataset — ${PROJECT_US}.${DATASET_RETAIL}" ;;
            regional_eu)  SECTION_LABEL="REGIONAL_EU dataset — ${PROJECT_EU}.${DATASET_REGIONAL}" ;;
            *)            SECTION_LABEL="$CURRENT_DATASET" ;;
        esac
        {
            echo ""
            echo "-- ============================================================================"
            echo "-- $SECTION_LABEL"
            echo "-- ============================================================================"
            echo ""
        } >> "$OUTPUT_FILE"
    fi

    # Apply variable substitution and append to output
    envsubst "$ENVSUBST_VARS" < "$SQL_FILE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Count tables and views
    if grep -q 'CREATE TABLE IF NOT EXISTS' "$SQL_FILE"; then
        TABLE_COUNT=$((TABLE_COUNT + 1))
    fi
    if grep -q 'CREATE OR REPLACE VIEW' "$SQL_FILE"; then
        VIEW_COUNT=$((VIEW_COUNT + 1))
    fi
    FILE_COUNT=$((FILE_COUNT + 1))

done < "$DEPLOY_ORDER"

echo "Generated: $OUTPUT_FILE"
echo "  Files processed: $FILE_COUNT"
echo "  Tables: $TABLE_COUNT"
echo "  Views: $VIEW_COUNT"
echo "  Total: $((TABLE_COUNT + VIEW_COUNT))"
