-- ============================================================================
-- BigQuery DDL: All Tables and Views (Auto-Generated)
-- ============================================================================
-- Generated by: scripts/generate_concat_ddl.sh
-- Source: ddl/deploy_order.txt + ddl/variables.env
--
-- This file contains all 100 CREATE TABLE and 15 CREATE OR REPLACE VIEW
-- statements in dependency-correct deployment order.
--
-- Usage:
--   bq query --use_legacy_sql=false --dry_run < ddl/all_tables.sql
--   bq query --use_legacy_sql=false < ddl/all_tables.sql
-- ============================================================================


-- ============================================================================
-- RAW dataset — acme-analytics.raw
-- ============================================================================

-- BigQuery DDL: raw.sales_retail
-- Source: Hive raw.sales_retail (acme-lake/hive/02-raw-external-tables.hql)
-- Partition: STRING date_ts → derived partition_date DATE
-- AC-5: partition_date DATE, date_ts STRING retained, unit_price NUMERIC, require_partition_filter

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.sales_retail`
(
    invoice_no     STRING,
    stock_code     STRING,
    description    STRING,
    quantity       INT64,
    invoice_date   STRING,
    unit_price     NUMERIC(10,2),
    customer_id    STRING,
    country        STRING,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date
OPTIONS (
    require_partition_filter = TRUE
);

-- BigQuery DDL: raw.omniture_logs
-- Source: Hive raw.omniture_logs (acme-lake/hive/02-raw-external-tables.hql)
-- 60-column STRING-only landing table for Omniture web-analytics logs.
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.omniture_logs`
(
    col_1 STRING, col_2 STRING, col_3 STRING, col_4 STRING, col_5 STRING,
    col_6 STRING, col_7 STRING, col_8 STRING, col_9 STRING, col_10 STRING,
    col_11 STRING, col_12 STRING, col_13 STRING, col_14 STRING, col_15 STRING,
    col_16 STRING, col_17 STRING, col_18 STRING, col_19 STRING, col_20 STRING,
    col_21 STRING, col_22 STRING, col_23 STRING, col_24 STRING, col_25 STRING,
    col_26 STRING, col_27 STRING, col_28 STRING, col_29 STRING, col_30 STRING,
    col_31 STRING, col_32 STRING, col_33 STRING, col_34 STRING, col_35 STRING,
    col_36 STRING, col_37 STRING, col_38 STRING, col_39 STRING, col_40 STRING,
    col_41 STRING, col_42 STRING, col_43 STRING, col_44 STRING, col_45 STRING,
    col_46 STRING, col_47 STRING, col_48 STRING, col_49 STRING, col_50 STRING,
    col_51 STRING, col_52 STRING, col_53 STRING, col_54 STRING, col_55 STRING,
    col_56 STRING, col_57 STRING, col_58 STRING, col_59 STRING, col_60 STRING,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.returns_cdc
-- Source: Hive raw.returns_cdc (acme-lake/hive/02-raw-external-tables.hql)
-- Partition: DATE snapshot_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.returns_cdc`
(
    return_id      INT64,
    invoice_no     STRING,
    customer_sk    INT64,
    return_ts      TIMESTAMP,
    refund_amount  NUMERIC(12,2),
    reason_code    STRING,
    status         STRING,
    op             STRING,
    snapshot_date  DATE
)
PARTITION BY snapshot_date;

-- BigQuery DDL: raw.pos_transactions
-- Source: Hive raw.pos_transactions (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.pos_transactions`
(
    txn_id          INT64,
    store_id        STRING,
    register_id     STRING,
    cashier_id      STRING,
    customer_id     STRING,
    invoice_no      STRING,
    txn_ts          TIMESTAMP,
    line_count      INT64,
    gross_amount    NUMERIC(14,2),
    discount_amount NUMERIC(14,2),
    tax_amount      NUMERIC(14,2),
    tender_type     STRING,
    void_flag       BOOL,
    date_ts         STRING,
    partition_date  DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.inventory_movements
-- Source: Hive raw.inventory_movements (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: multi-col (year INT, month INT, day INT) → generated partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.inventory_movements`
(
    movement_id    INT64,
    sku            STRING,
    warehouse_id   STRING,
    bin_location   STRING,
    movement_type  STRING,
    quantity       INT64,
    movement_ts    TIMESTAMP,
    reference_doc  STRING,
    operator_id    STRING,
    reason_code    STRING,
    year           INT64,
    month          INT64,
    day            INT64,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.customer_signups
-- Source: Hive raw.customer_signups (Avro schema: customer_signups-v3.avsc)
-- Category: avro_net_new (absent from live Hive metastore)
-- Partition: STRING signup_date → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.customer_signups`
(
    customer_id    STRING,
    email          STRING,
    phone          STRING,
    first_name     STRING,
    last_name      STRING,
    addr_line1     STRING,
    addr_city      STRING,
    addr_region    STRING,
    addr_country   STRING,
    addr_postal    STRING,
    signup_source  STRING,
    marketing_opt_in BOOL,
    signup_date    STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.loyalty_events
-- Source: Hive raw.loyalty_events (acme-lake/hive/05-additional-raw-feeds.hql)
-- RegexSerDe feed; meta_raw is STRING in source (not MAP), stays STRING.
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.loyalty_events`
(
    event_ts_str   STRING,
    member_id      STRING,
    event_type     STRING,
    points         STRING,
    store_id       STRING,
    tx_id          STRING,
    meta_raw       STRING,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.product_catalog_feed
-- Source: Hive raw.product_catalog_feed (acme-lake/hive/05-additional-raw-feeds.hql)
-- MAP<STRING,STRING> metadata → JSON
-- Partition: STRING feed_date → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.product_catalog_feed`
(
    sku            STRING,
    supplier_id    STRING,
    upc            STRING,
    name           STRING,
    category       STRING,
    subcategory    STRING,
    color          STRING,
    size           STRING,
    msrp           NUMERIC(10,2),
    cost           NUMERIC(10,2),
    available_from DATE,
    discontinued_at DATE,
    metadata       JSON,
    feed_date      STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.supplier_invoices
-- Source: Hive raw.supplier_invoices (acme-lake/hive/05-additional-raw-feeds.hql)
-- ARRAY<STRUCT<...>> with type widening applied
-- Partition: multi-col (feed_year INT, feed_month INT) → generated partition_month DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.supplier_invoices`
(
    invoice_no    STRING,
    supplier_id   STRING,
    invoice_date  DATE,
    due_date      DATE,
    total_amount  NUMERIC(14,2),
    currency      STRING,
    line_items    ARRAY<STRUCT<sku STRING, qty INT64, unit_price NUMERIC(10,2)>>,
    raw_xml       STRING,
    feed_year     INT64,
    feed_month    INT64,
    partition_month DATE
)
PARTITION BY partition_month;

-- BigQuery DDL: raw.email_campaign_clicks
-- Source: Hive raw.email_campaign_clicks (acme-lake/hive/05-additional-raw-feeds.hql)
-- MAP<STRING,STRING> utm → JSON (AC-13: source column name is `utm`, not `utm_params`)
-- STRUCT geo preserved with direct mapping
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.email_campaign_clicks`
(
    campaign_id  STRING,
    send_id      STRING,
    recipient    STRING,
    clicked_at   TIMESTAMP,
    click_url    STRING,
    user_agent   STRING,
    ip_address   STRING,
    geo          STRUCT<country STRING, region STRING, city STRING>,
    utm          JSON,
    date_ts      STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.shipment_tracking
-- Source: Hive raw.shipment_tracking (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: STRING date_ts + STRING carrier_partition → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.shipment_tracking`
(
    tracking_no   STRING,
    carrier       STRING,
    invoice_no    STRING,
    customer_id   STRING,
    shipped_at    TIMESTAMP,
    delivered_at  TIMESTAMP,
    status        STRING,
    last_location STRING,
    estimated_eta TIMESTAMP,
    date_ts       STRING,
    carrier_partition STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.return_authorizations
-- Source: Hive raw.return_authorizations (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.return_authorizations`
(
    rma_id          STRING,
    customer_id     STRING,
    invoice_no      STRING,
    stock_code      STRING,
    quantity        INT64,
    reason_code     STRING,
    reason_text     STRING,
    requested_at    TIMESTAMP,
    approved        BOOL,
    refund_amount   NUMERIC(12,2),
    date_ts         STRING,
    partition_date  DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.fraud_signals
-- Source: Hive raw.fraud_signals (Avro schema: fraud_signals-v5.avsc)
-- Category: avro_net_new (absent from live Hive metastore)
-- Partition: STRING signal_date → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.fraud_signals`
(
    customer_id    STRING,
    signal_type    STRING,
    score          FLOAT64,
    risk_band      STRING,
    reason_codes   ARRAY<STRING>,
    signal_ts      TIMESTAMP,
    vendor         STRING,
    signal_date    STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.warehouse_picks
-- Source: Hive raw.warehouse_picks (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: STRING date_ts + STRING warehouse_id_partition → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.warehouse_picks`
(
    pick_id        INT64,
    warehouse_id   STRING,
    bin_id         STRING,
    sku            STRING,
    picker_id      STRING,
    quantity       INT64,
    picked_at      TIMESTAMP,
    duration_ms    INT64,
    date_ts        STRING,
    warehouse_id_partition STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.delivery_routes
-- Source: Hive raw.delivery_routes (acme-lake/hive/05-additional-raw-feeds.hql)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.delivery_routes`
(
    route_id       STRING,
    driver_id      STRING,
    vehicle_id     STRING,
    planned_stops  INT64,
    actual_stops   INT64,
    miles_driven   NUMERIC(8,2),
    fuel_used      NUMERIC(8,2),
    start_ts       TIMESTAMP,
    end_ts         TIMESTAMP,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.driver_logs
-- Source: Hive raw.driver_logs (acme-lake/hive/05-additional-raw-feeds.hql)
-- STRUCT<lat:DOUBLE, lon:DOUBLE> → STRUCT<lat FLOAT64, lon FLOAT64>
-- MAP<STRING,STRING> extras → JSON
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.driver_logs`
(
    driver_id    STRING,
    event_ts     TIMESTAMP,
    event_type   STRING,
    gps          STRUCT<lat FLOAT64, lon FLOAT64>,
    notes        STRING,
    extras       JSON,
    date_ts      STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.customer_complaints
-- Source: Hive raw.customer_complaints (acme-lake/hive/05-additional-raw-feeds.hql)
-- AC-13 note: resolution_details column absent in source schema — AC exception documented
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.customer_complaints`
(
    complaint_id  STRING,
    customer_id   STRING,
    invoice_no    STRING,
    channel       STRING,
    severity      STRING,
    summary       STRING,
    body          STRING,
    created_at    TIMESTAMP,
    resolved_at   TIMESTAMP,
    csat_score    INT64,
    date_ts       STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.chat_transcripts
-- Source: Hive raw.chat_transcripts (acme-lake/hive/05-additional-raw-feeds.hql)
-- AC-13 note: session_metadata column absent in source schema — AC exception documented
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.chat_transcripts`
(
    chat_id        STRING,
    customer_id    STRING,
    agent_id       STRING,
    started_at     TIMESTAMP,
    ended_at       TIMESTAMP,
    duration_sec   INT64,
    message_count  INT64,
    transcript     STRING,
    sentiment      NUMERIC(4,3),
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: raw.mobile_events
-- Source: Hive raw.mobile_events (acme-lake/hive/07-json-raw.hql)
-- AC-6: properties JSON, context STRUCT<ip_address STRING, ...>,
--        items ARRAY<STRUCT<...>>, PARTITION BY partition_date,
--        CLUSTER BY platform, hour_bucket
-- Type mappings: MAP→JSON, STRUCT ip→ip_address, INT→INT64, DECIMAL→NUMERIC, TINYINT→INT64

CREATE TABLE IF NOT EXISTS `acme-analytics.raw.mobile_events`
(
    event_id        STRING,
    event_ts        TIMESTAMP,
    user_id         STRING,
    app_version     STRING,
    device_type     STRING,
    platform        STRING,
    properties      JSON,
    context         STRUCT<ip_address STRING, country STRING, session_id STRING, referrer STRING>,
    items           ARRAY<STRUCT<sku STRING, qty INT64, price NUMERIC(10,2)>>,
    event_date      STRING,
    hour_bucket     INT64,
    partition_date  DATE
)
PARTITION BY partition_date
CLUSTER BY platform, hour_bucket;

-- BigQuery View: raw.omniture
-- Source: Hive raw.omniture (acme-lake/hive/02-raw-external-tables.hql)
-- Thin projection view over omniture_logs (60-col STRING landing table).
-- Translation: direct mapping, fully-qualified table reference added.

CREATE OR REPLACE VIEW `acme-analytics.raw.omniture` AS
SELECT
    col_2  AS event_ts,
    col_8  AS ip,
    col_13 AS url,
    col_14 AS user_id,
    col_50 AS city,
    col_51 AS country,
    col_53 AS state,
    date_ts
FROM `acme-analytics.raw.omniture_logs`;

-- BigQuery View: raw.v_fraud_signals_recent
-- Source: Hive raw.v_fraud_signals_recent (acme-lake/hive/05-additional-raw-feeds.hql)
-- Translation:
--   date_format(date_sub(current_date(), 1), 'yyyyMMdd')
--     → FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))

CREATE OR REPLACE VIEW `acme-analytics.raw.v_fraud_signals_recent` AS
SELECT *
FROM `acme-analytics.raw.fraud_signals`
WHERE signal_date >= FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY));


-- ============================================================================
-- STAGING dataset — acme-analytics.staging
-- ============================================================================

-- BigQuery DDL: staging.cleansed_orders
-- Source: Hive staging.cleansed_orders (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE order_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.cleansed_orders`
(
    order_id       STRING,
    customer_id    STRING,
    invoice_no     STRING,
    txn_ts         TIMESTAMP,
    line_count     INT64,
    gross_amount   NUMERIC(14,2),
    discount       NUMERIC(14,2),
    tax            NUMERIC(14,2),
    net_amount     NUMERIC(14,2),
    tender_type    STRING,
    source_feed    STRING,
    order_date     DATE
)
PARTITION BY order_date;

-- BigQuery DDL: staging.cleansed_customers
-- Source: Hive staging.cleansed_customers (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE load_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.cleansed_customers`
(
    customer_id     STRING,
    email_norm      STRING,
    phone_norm      STRING,
    first_name      STRING,
    last_name       STRING,
    addr_line1      STRING,
    addr_city       STRING,
    addr_region     STRING,
    addr_country    STRING,
    addr_postal     STRING,
    geocoded_lat    FLOAT64,
    geocoded_lon    FLOAT64,
    eff_from_ts     TIMESTAMP,
    record_hash     STRING,
    load_date       DATE
)
PARTITION BY load_date;

-- BigQuery DDL: staging.cleansed_products
-- Source: Hive staging.cleansed_products (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE load_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.cleansed_products`
(
    sku            STRING,
    upc            STRING,
    name_norm      STRING,
    category_norm  STRING,
    subcategory    STRING,
    color_norm     STRING,
    size_norm      STRING,
    msrp           NUMERIC(10,2),
    cost           NUMERIC(10,2),
    supplier_id    STRING,
    available      BOOL,
    load_date      DATE
)
PARTITION BY load_date;

-- BigQuery DDL: staging.dedup_clickstream
-- Source: Hive staging.dedup_clickstream (acme-lake/hive/06-staging-tables.hql)
-- Partition: STRING date_ts + STRING country_partition → derived partition_date DATE
-- Clustering: CLUSTERED BY (user_id) INTO 16 BUCKETS → CLUSTER BY user_id

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.dedup_clickstream`
(
    session_id     STRING,
    user_id        STRING,
    event_ts       TIMESTAMP,
    page_url       STRING,
    referrer_url   STRING,
    ip             STRING,
    country        STRING,
    bot_score      NUMERIC(4,3),
    device_type    STRING,
    date_ts        STRING,
    country_partition STRING,
    partition_date DATE
)
PARTITION BY partition_date
CLUSTER BY user_id;

-- BigQuery DDL: staging.geocoded_addresses
-- Source: Hive staging.geocoded_addresses (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE load_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.geocoded_addresses`
(
    raw_addr_hash  STRING,
    addr_line1     STRING,
    addr_city      STRING,
    addr_region    STRING,
    addr_country   STRING,
    addr_postal    STRING,
    lat            FLOAT64,
    lon            FLOAT64,
    confidence     NUMERIC(4,3),
    provider       STRING,
    load_date      DATE
)
PARTITION BY load_date;

-- BigQuery DDL: staging.parsed_loyalty_events
-- Source: Hive staging.parsed_loyalty_events (acme-lake/hive/06-staging-tables.hql)
-- MAP<STRING,STRING> meta → JSON (AC-13)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.parsed_loyalty_events`
(
    event_ts       TIMESTAMP,
    member_id      STRING,
    event_type     STRING,
    points         INT64,
    store_id       STRING,
    tx_id          STRING,
    meta           JSON,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: staging.merged_returns_cdc
-- Source: Hive staging.merged_returns_cdc (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE snapshot_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.merged_returns_cdc`
(
    return_id      INT64,
    invoice_no     STRING,
    customer_sk    INT64,
    return_ts      TIMESTAMP,
    refund_amount  NUMERIC(12,2),
    reason_code    STRING,
    status         STRING,
    is_deleted     BOOL,
    snapshot_date  DATE
)
PARTITION BY snapshot_date;

-- BigQuery DDL: staging.normalized_carrier_events
-- Source: Hive staging.normalized_carrier_events (acme-lake/hive/06-staging-tables.hql)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.normalized_carrier_events`
(
    tracking_no    STRING,
    carrier        STRING,
    event_type     STRING,
    event_ts       TIMESTAMP,
    location_city  STRING,
    location_region STRING,
    location_country STRING,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: staging.fraud_scored
-- Source: Hive staging.fraud_scored (acme-lake/hive/06-staging-tables.hql)
-- Partition: DATE score_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.fraud_scored`
(
    txn_id         INT64,
    customer_id    STRING,
    fraud_score    NUMERIC(5,4),
    risk_band      STRING,
    signals        ARRAY<STRING>,
    scored_at      TIMESTAMP,
    score_date     DATE
)
PARTITION BY score_date;

-- BigQuery DDL: staging.warehouse_kpi_snapshot
-- Source: Hive staging.warehouse_kpi_snapshot (acme-lake/hive/06-staging-tables.hql)
-- Partition: STRING date_ts → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.staging.warehouse_kpi_snapshot`
(
    warehouse_id   STRING,
    snapshot_ts    TIMESTAMP,
    units_in       INT64,
    units_picked   INT64,
    units_shipped  INT64,
    pick_rate_uph  NUMERIC(8,2),
    backlog_units  INT64,
    avg_pick_ms    INT64,
    date_ts        STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery View: staging.v_returns_pending
-- Source: Hive staging.v_returns_pending (acme-lake/hive/06-staging-tables.hql)
-- Translation:
--   DATEDIFF(current_date(), to_date(r.requested_at))
--     → DATE_DIFF(CURRENT_DATE(), DATE(r.requested_at), DAY)

CREATE OR REPLACE VIEW `acme-analytics.staging.v_returns_pending` AS
SELECT
    r.rma_id,
    r.customer_id,
    r.invoice_no,
    r.stock_code,
    r.quantity,
    r.requested_at,
    DATE_DIFF(CURRENT_DATE(), DATE(r.requested_at), DAY) AS days_pending
FROM `acme-analytics.raw.return_authorizations` r
WHERE r.approved IS NULL OR r.approved = FALSE;


-- ============================================================================
-- RETAIL dataset — acme-analytics.retail
-- ============================================================================

-- BigQuery DDL: retail.dim_date
-- Source: Hive retail.dim_date (acme-analytics/hive/03-retail-tables.hql)
-- No partition (small dimension table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_date`
(
    d_date_sk      INT64,
    d_date_id      STRING,
    d_date         DATE,
    d_month_seq    INT64,
    d_week_seq     INT64,
    d_quarter_seq  INT64,
    d_year         INT64,
    d_dow          INT64,
    d_moy          INT64,
    d_dom          INT64,
    d_qoy          INT64,
    d_fy_year      INT64,
    d_fy_quarter_seq INT64,
    d_day_name     STRING,
    d_holiday      STRING,
    d_weekend      STRING,
    d_following_holiday STRING,
    d_first_dom    INT64,
    d_last_dom     INT64,
    d_same_day_ly  INT64,
    d_same_day_lq  INT64,
    d_current_day  STRING,
    d_current_week STRING,
    d_current_month STRING,
    d_current_quarter STRING,
    d_current_year STRING
);

-- BigQuery DDL: retail.dim_customer
-- Source: Hive retail.dim_customer (acme-analytics/hive/03-retail-tables.hql)
-- No partition (small dimension table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_customer`
(
    customer_sk    INT64,
    customer_id    STRING,
    country        STRING,
    first_seen_ts  TIMESTAMP,
    last_seen_ts   TIMESTAMP
);

-- BigQuery DDL: retail.dim_product
-- Source: Hive retail.dim_product (acme-analytics/hive/03-retail-tables.hql)
-- No partition (small dimension table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_product`
(
    product_sk     INT64,
    stock_code     STRING,
    description    STRING,
    unit_price     NUMERIC(10,2)
);

-- BigQuery DDL: retail.dim_store
-- Source: Hive retail.dim_store (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new (absent from live Hive metastore)
-- MAP<STRING,STRING> attributes → JSON

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_store`
(
    store_sk        INT64,
    store_id        STRING,
    store_name      STRING,
    store_type      STRING,
    region          STRING,
    city            STRING,
    state           STRING,
    country         STRING,
    open_dt         DATE,
    close_dt        DATE,
    sq_ft           INT64,
    manager_employee_sk INT64,
    attributes      JSON
);

-- BigQuery DDL: retail.dim_supplier
-- Source: Hive retail.dim_supplier (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new
-- STRUCT<name:STRING, email:STRING, phone:STRING> preserved
-- ARRAY<STRING> categories preserved

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_supplier`
(
    supplier_sk      INT64,
    supplier_id      STRING,
    supplier_name    STRING,
    country          STRING,
    tax_id           STRING,
    payment_terms_days INT64,
    onboard_dt       DATE,
    risk_rating      STRING,
    primary_contact  STRUCT<name STRING, email STRING, phone STRING>,
    categories       ARRAY<STRING>
);

-- BigQuery DDL: retail.dim_employee
-- Source: Hive retail.dim_employee (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_employee`
(
    employee_sk     INT64,
    employee_id     STRING,
    first_name      STRING,
    last_name       STRING,
    hire_dt         DATE,
    termination_dt  DATE,
    role            STRING,
    department      STRING,
    home_store_sk   INT64,
    manager_sk      INT64,
    salary_band     STRING
);

-- BigQuery DDL: retail.dim_promotion
-- Source: Hive retail.dim_promotion (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new
-- MAP<STRING,STRING> eligibility → JSON
-- ARRAY<STRING> channels preserved

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_promotion`
(
    promo_sk        INT64,
    promo_id        STRING,
    name            STRING,
    promo_type      STRING,
    pct_off         NUMERIC(5,2),
    flat_off        NUMERIC(10,2),
    start_dt        DATE,
    end_dt          DATE,
    budget          NUMERIC(14,2),
    channels        ARRAY<STRING>,
    eligibility     JSON
);

-- BigQuery DDL: retail.dim_warehouse
-- Source: Hive retail.dim_warehouse (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new
-- STRUCT<lat:DOUBLE, lon:DOUBLE> → STRUCT<lat FLOAT64, lon FLOAT64>

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_warehouse`
(
    warehouse_sk    INT64,
    warehouse_id    STRING,
    name            STRING,
    type            STRING,
    operator        STRING,
    region          STRING,
    capacity_units  INT64,
    open_dt         DATE,
    geocode         STRUCT<lat FLOAT64, lon FLOAT64>
);

-- BigQuery DDL: retail.dim_currency
-- Source: Hive retail.dim_currency (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_currency`
(
    currency_code   STRING,
    currency_name   STRING,
    minor_unit      INT64,
    symbol          STRING
);

-- BigQuery DDL: retail.dim_geography
-- Source: Hive retail.dim_geography (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_geography`
(
    geo_sk           INT64,
    country_iso2     STRING,
    country_name     STRING,
    region_code      STRING,
    region_name      STRING,
    city             STRING,
    postal_code      STRING,
    timezone         STRING,
    latitude         FLOAT64,
    longitude        FLOAT64
);

-- BigQuery DDL: retail.dim_color
-- Source: Hive retail.dim_color (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_color`
(
    color_sk        INT64,
    color_code      STRING,
    color_name      STRING,
    color_family    STRING,
    hex_code        STRING
);

-- BigQuery DDL: retail.dim_size
-- Source: Hive retail.dim_size (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_size`
(
    size_sk         INT64,
    size_code       STRING,
    size_name       STRING,
    size_system     STRING,
    sort_order      INT64
);

-- BigQuery DDL: retail.dim_brand
-- Source: Hive retail.dim_brand (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_brand`
(
    brand_sk        INT64,
    brand_id        STRING,
    brand_name      STRING,
    parent_company  STRING,
    private_label   BOOL,
    launch_dt       DATE
);

-- BigQuery DDL: retail.dim_category
-- Source: Hive retail.dim_category (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new (self-referencing hierarchy)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_category`
(
    category_sk     INT64,
    category_id     STRING,
    parent_id       STRING,
    name            STRING,
    depth           INT64,
    sort_order      INT64
);

-- BigQuery DDL: retail.dim_payment_method
-- Source: Hive retail.dim_payment_method (acme-analytics/hive/10-additional-dims.hql)
-- Category: dim_net_new

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_payment_method`
(
    payment_method_sk INT64,
    method_code       STRING,
    method_name       STRING,
    category          STRING,
    fee_pct           NUMERIC(5,4),
    fee_flat          NUMERIC(8,2),
    settlement_days   INT64
);

-- BigQuery DDL: retail.fact_sales
-- Source: Hive retail.fact_sales (acme-analytics/hive/03-retail-tables.hql)
-- AC-7: unit_price NUMERIC, line_total NUMERIC, sale_date DATE partition, cluster customer_sk
-- Partition: DATE sale_date (direct passthrough)
-- Clustering: CLUSTERED BY (customer_sk) INTO 8 BUCKETS → CLUSTER BY customer_sk

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_sales`
(
    invoice_no     STRING,
    customer_sk    INT64,
    product_sk     INT64,
    quantity       INT64,
    unit_price     NUMERIC(10,2),
    line_total     NUMERIC(14,2),
    country        STRING,
    invoice_ts     TIMESTAMP,
    sale_date      DATE
)
PARTITION BY sale_date
CLUSTER BY customer_sk;

-- BigQuery DDL: retail.fact_web_session
-- Source: Hive retail.fact_web_session (acme-analytics/hive/03-retail-tables.hql)
-- Partition: DATE event_date (direct passthrough; country partition dropped to regular column)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_web_session`
(
    event_ts       TIMESTAMP,
    ip             STRING,
    url            STRING,
    user_id        STRING,
    city           STRING,
    state          STRING,
    event_date     DATE,
    country        STRING
)
PARTITION BY event_date;

-- BigQuery DDL: retail.fact_inventory_movements
-- Source: Hive retail.fact_inventory_movements (acme-analytics/hive/11-additional-facts.hql)
-- AC-8: partition by DATE(year, month, day), cluster by region
-- Multi-col partition (year/month/day/region) → generated partition_date DATE
-- Clustering: CLUSTERED BY (sku) INTO 32 BUCKETS → CLUSTER BY region (per AC-8)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_inventory_movements`
(
    movement_id    INT64,
    movement_ts    TIMESTAMP,
    sku            STRING,
    warehouse_sk   INT64,
    store_sk       INT64,
    movement_type  STRING,
    quantity       INT64,
    reference_doc  STRING,
    reason_code    STRING,
    operator_sk    INT64,
    year           INT64,
    month          INT64,
    day            INT64,
    region         STRING,
    partition_date DATE
)
PARTITION BY partition_date
CLUSTER BY region;

-- BigQuery DDL: retail.fact_inventory_snapshot
-- Source: Hive retail.fact_inventory_snapshot (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE snapshot_date (direct passthrough)
-- Clustering: CLUSTERED BY (sku) INTO 16 BUCKETS → CLUSTER BY sku

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_inventory_snapshot`
(
    sku            STRING,
    warehouse_sk   INT64,
    on_hand_units  INT64,
    allocated_units INT64,
    in_transit_units INT64,
    available_units INT64,
    avg_cost       NUMERIC(12,4),
    last_movement_ts TIMESTAMP,
    snapshot_date  DATE
)
PARTITION BY snapshot_date
CLUSTER BY sku;

-- BigQuery DDL: retail.fact_returns
-- Source: Hive retail.fact_returns (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE return_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_returns`
(
    return_id       INT64,
    invoice_no      STRING,
    customer_sk     INT64,
    product_sk      INT64,
    return_ts       TIMESTAMP,
    quantity        INT64,
    refund_amount   NUMERIC(12,2),
    reason_code     STRING,
    return_channel  STRING,
    store_sk        INT64,
    return_date     DATE
)
PARTITION BY return_date;

-- BigQuery DDL: retail.fact_payments
-- Source: Hive retail.fact_payments (acme-analytics/hive/11-additional-facts.hql)
-- AC-9: partition by DATE(post_year, post_month, 1), cluster by payment_method_partition
-- Multi-col partition (post_year/post_month/payment_method_partition) → generated partition_month DATE
-- Clustering: CLUSTERED BY (invoice_no) INTO 16 BUCKETS → CLUSTER BY payment_method_partition (per AC-9)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_payments`
(
    payment_id      INT64,
    invoice_no      STRING,
    customer_sk     INT64,
    payment_method_sk INT64,
    amount          NUMERIC(14,2),
    currency_code   STRING,
    payment_ts      TIMESTAMP,
    auth_code       STRING,
    settlement_id   STRING,
    fee_amount      NUMERIC(10,2),
    post_year       INT64,
    post_month      INT64,
    payment_method_partition STRING,
    partition_month DATE
)
PARTITION BY partition_month
CLUSTER BY payment_method_partition;

-- BigQuery DDL: retail.fact_shipments
-- Source: Hive retail.fact_shipments (acme-analytics/hive/11-additional-facts.hql)
-- ARRAY<STRUCT<ts:TIMESTAMP, status:STRING, location:STRING>> preserved
-- Multi-col partition (ship_year/ship_month/ship_day/carrier_partition) → generated partition_date DATE
-- Clustering: CLUSTERED BY (warehouse_sk) INTO 16 BUCKETS → CLUSTER BY warehouse_sk

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_shipments`
(
    shipment_id     STRING,
    invoice_no      STRING,
    customer_sk     INT64,
    warehouse_sk    INT64,
    carrier         STRING,
    tracking_no     STRING,
    shipped_ts      TIMESTAMP,
    delivered_ts    TIMESTAMP,
    sla_hours       INT64,
    tracking_events ARRAY<STRUCT<ts TIMESTAMP, status STRING, location STRING>>,
    ship_year       INT64,
    ship_month      INT64,
    ship_day        INT64,
    carrier_partition STRING,
    partition_date  DATE
)
PARTITION BY partition_date
CLUSTER BY warehouse_sk;

-- BigQuery DDL: retail.fact_refunds
-- Source: Hive retail.fact_refunds (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE refund_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_refunds`
(
    refund_id       INT64,
    payment_id      INT64,
    return_id       INT64,
    customer_sk     INT64,
    amount          NUMERIC(14,2),
    currency_code   STRING,
    refund_ts       TIMESTAMP,
    refund_method   STRING,
    refund_date     DATE
)
PARTITION BY refund_date;

-- BigQuery DDL: retail.fact_app_clicks
-- Source: Hive retail.fact_app_clicks (acme-analytics/hive/11-additional-facts.hql)
-- MAP<STRING,STRING> properties → JSON
-- STRUCT<platform:STRING, version:STRING, model:STRING> preserved
-- Partition: DATE event_date (direct; platform_partition dropped to regular column)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_app_clicks`
(
    session_id      STRING,
    user_sk         INT64,
    event_ts        TIMESTAMP,
    event_type      STRING,
    screen          STRING,
    target_id       STRING,
    properties      JSON,
    device          STRUCT<platform STRING, version STRING, model STRING>,
    event_date      DATE,
    platform_partition STRING
)
PARTITION BY event_date;

-- BigQuery DDL: retail.fact_email_engagement
-- Source: Hive retail.fact_email_engagement (acme-analytics/hive/11-additional-facts.hql)
-- ARRAY<STRUCT<ts:TIMESTAMP, url:STRING>> preserved
-- Partition: DATE event_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_email_engagement`
(
    send_id         STRING,
    campaign_sk     INT64,
    user_sk         INT64,
    event_type      STRING,
    event_ts        TIMESTAMP,
    link_url        STRING,
    clicks          ARRAY<STRUCT<ts TIMESTAMP, url STRING>>,
    event_date      DATE
)
PARTITION BY event_date;

-- BigQuery DDL: retail.fact_chat_interactions
-- Source: Hive retail.fact_chat_interactions (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE start_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_chat_interactions`
(
    chat_id          STRING,
    customer_sk      INT64,
    agent_sk         INT64,
    started_at       TIMESTAMP,
    ended_at         TIMESTAMP,
    duration_sec     INT64,
    message_count    INT64,
    resolved         BOOL,
    csat_score       INT64,
    sentiment_avg    NUMERIC(4,3),
    start_date       DATE
)
PARTITION BY start_date;

-- BigQuery DDL: retail.fact_warehouse_picks
-- Source: Hive retail.fact_warehouse_picks (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE pick_date (direct; warehouse_partition dropped to regular column)
-- Clustering: CLUSTERED BY (picker_sk) INTO 8 BUCKETS → CLUSTER BY picker_sk

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_warehouse_picks`
(
    pick_id          INT64,
    warehouse_sk     INT64,
    picker_sk        INT64,
    sku              STRING,
    quantity         INT64,
    picked_ts        TIMESTAMP,
    duration_ms      INT64,
    bin_location     STRING,
    pick_date        DATE,
    warehouse_partition STRING
)
PARTITION BY pick_date
CLUSTER BY picker_sk;

-- BigQuery DDL: retail.fact_supplier_invoice_lines
-- Source: Hive retail.fact_supplier_invoice_lines (acme-analytics/hive/11-additional-facts.hql)
-- Multi-col partition (invoice_year/invoice_month) → generated partition_month DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_supplier_invoice_lines`
(
    invoice_line_id  INT64,
    invoice_no       STRING,
    supplier_sk      INT64,
    sku              STRING,
    quantity         INT64,
    unit_cost        NUMERIC(12,4),
    line_total       NUMERIC(14,2),
    currency_code    STRING,
    received_ts      TIMESTAMP,
    invoice_year     INT64,
    invoice_month    INT64,
    partition_month  DATE
)
PARTITION BY partition_month;

-- BigQuery DDL: retail.fact_loyalty_events
-- Source: Hive retail.fact_loyalty_events (acme-analytics/hive/11-additional-facts.hql)
-- MAP<STRING,STRING> meta → JSON (AC-13)
-- Partition: DATE event_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_loyalty_events`
(
    event_id        INT64,
    member_id       STRING,
    event_type      STRING,
    points          INT64,
    store_sk        INT64,
    tx_id           STRING,
    event_ts        TIMESTAMP,
    meta            JSON,
    event_date      DATE
)
PARTITION BY event_date;

-- BigQuery DDL: retail.fact_fraud_decisions
-- Source: Hive retail.fact_fraud_decisions (acme-analytics/hive/11-additional-facts.hql)
-- ARRAY<STRING> rule_signals preserved
-- Partition: DATE decision_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_fraud_decisions`
(
    txn_id          INT64,
    customer_sk     INT64,
    fraud_score     NUMERIC(5,4),
    decision        STRING,
    rule_signals    ARRAY<STRING>,
    decided_ts      TIMESTAMP,
    decision_date   DATE
)
PARTITION BY decision_date;

-- BigQuery DDL: retail.fact_promo_redemptions
-- Source: Hive retail.fact_promo_redemptions (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE redemption_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_promo_redemptions`
(
    redemption_id   INT64,
    promo_sk        INT64,
    invoice_no      STRING,
    customer_sk     INT64,
    discount_amount NUMERIC(12,2),
    applied_ts      TIMESTAMP,
    channel         STRING,
    redemption_date DATE
)
PARTITION BY redemption_date;

-- BigQuery DDL: retail.fact_customer_complaints
-- Source: Hive retail.fact_customer_complaints (acme-analytics/hive/11-additional-facts.hql)
-- Partition: DATE created_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.fact_customer_complaints`
(
    complaint_id    STRING,
    customer_sk     INT64,
    invoice_no      STRING,
    channel         STRING,
    severity        STRING,
    summary         STRING,
    created_at      TIMESTAMP,
    resolved_at     TIMESTAMP,
    csat_score      INT64,
    created_date    DATE
)
PARTITION BY created_date;

-- BigQuery DDL: retail.sales_cube
-- Source: Hive retail.sales_cube (acme-analytics/hive/08-rollup-etl.hql)
-- TINYINT dim_level → INT64, SMALLINT month_key → INT64
-- Partition: DATE as_of_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.sales_cube`
(
    dim_level       INT64,
    cube_key        STRING,
    country         STRING,
    month_key       INT64,
    product_sk      INT64,
    orders          INT64,
    revenue         NUMERIC(18,2),
    units           INT64,
    as_of_date      DATE
)
PARTITION BY as_of_date;

-- BigQuery DDL: retail.top_countries_daily
-- Source: Hive retail.top_countries_daily (acme-analytics/hive/08-rollup-etl.hql)
-- TINYINT rank → INT64
-- No partition (small rollup table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.top_countries_daily`
(
    as_of_date   DATE,
    country      STRING,
    orders       INT64,
    revenue      NUMERIC(18,2),
    rank         INT64
);

-- BigQuery DDL: retail.agg_daily_sales_by_store
-- Source: Hive retail.agg_daily_sales_by_store (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE sale_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_daily_sales_by_store`
(
    store_sk            INT64,
    gross_revenue       NUMERIC(16,2),
    net_revenue         NUMERIC(16,2),
    units_sold          INT64,
    txn_count           INT64,
    avg_basket          NUMERIC(12,2),
    sale_date           DATE
)
PARTITION BY sale_date;

-- BigQuery DDL: retail.agg_daily_sales_by_product
-- Source: Hive retail.agg_daily_sales_by_product (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE sale_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_daily_sales_by_product`
(
    product_sk          INT64,
    units_sold          INT64,
    gross_revenue       NUMERIC(16,2),
    margin_pct          NUMERIC(6,4),
    cogs                NUMERIC(16,2),
    return_units        INT64,
    net_units           INT64,
    sale_date           DATE
)
PARTITION BY sale_date;

-- BigQuery DDL: retail.agg_weekly_customer_ltv
-- Source: Hive retail.agg_weekly_customer_ltv (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE week_start_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_weekly_customer_ltv`
(
    customer_sk         INT64,
    ltv_to_date         NUMERIC(16,2),
    orders_to_date      INT64,
    avg_order_value     NUMERIC(12,2),
    days_since_last_order INT64,
    rfm_score           STRING,
    churn_risk          NUMERIC(4,3),
    week_start_date     DATE
)
PARTITION BY week_start_date;

-- BigQuery DDL: retail.agg_monthly_supplier_performance
-- Source: Hive retail.agg_monthly_supplier_performance (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE month_start (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_monthly_supplier_performance`
(
    supplier_sk         INT64,
    orders_placed       INT64,
    units_received      INT64,
    on_time_pct         NUMERIC(5,4),
    fill_rate_pct       NUMERIC(5,4),
    avg_lead_time_days  NUMERIC(6,2),
    quality_score       NUMERIC(4,3),
    total_spend         NUMERIC(16,2),
    month_start         DATE
)
PARTITION BY month_start;

-- BigQuery DDL: retail.agg_hourly_warehouse_kpi
-- Source: Hive retail.agg_hourly_warehouse_kpi (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: STRING snapshot_hour → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_hourly_warehouse_kpi`
(
    warehouse_sk        INT64,
    units_in            INT64,
    units_picked        INT64,
    units_shipped       INT64,
    pick_rate_uph       NUMERIC(8,2),
    backlog_units       INT64,
    avg_pick_seconds    NUMERIC(8,2),
    snapshot_hour       STRING,
    partition_date      DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: retail.agg_daily_carrier_otd
-- Source: Hive retail.agg_daily_carrier_otd (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE ship_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_daily_carrier_otd`
(
    carrier             STRING,
    shipments_total     INT64,
    delivered_on_time   INT64,
    delivered_late      INT64,
    in_transit          INT64,
    otd_pct             NUMERIC(5,4),
    avg_transit_hours   NUMERIC(8,2),
    ship_date           DATE
)
PARTITION BY ship_date;

-- BigQuery DDL: retail.agg_marketing_attribution_cube
-- Source: Hive retail.agg_marketing_attribution_cube (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE period_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_marketing_attribution_cube`
(
    channel             STRING,
    campaign_sk         INT64,
    region              STRING,
    attributed_revenue  NUMERIC(16,2),
    attributed_units    INT64,
    cost                NUMERIC(14,2),
    roas                NUMERIC(8,4),
    grouping_id         INT64,
    period_date         DATE
)
PARTITION BY period_date;

-- BigQuery DDL: retail.agg_returns_by_reason_monthly
-- Source: Hive retail.agg_returns_by_reason_monthly (acme-analytics/hive/12-aggregates-rollups.hql)
-- Partition: DATE month_start (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.agg_returns_by_reason_monthly`
(
    reason_code         STRING,
    return_count        INT64,
    return_units        INT64,
    total_refunded      NUMERIC(16,2),
    avg_days_to_return  NUMERIC(8,2),
    month_start         DATE
)
PARTITION BY month_start;

-- BigQuery DDL: retail.returns_ledger
-- Source: Hive retail.returns_ledger (acme-analytics/hive/06-acid-tables.hql)
-- AC-10: refund_amount NUMERIC, no ORC/bucketing properties (plain BigQuery table)
-- AC-14: ACID table → standard BigQuery managed table, DECIMAL→NUMERIC
-- Clustering: CLUSTERED BY (return_id) INTO 4 BUCKETS → CLUSTER BY return_id

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.returns_ledger`
(
    return_id       INT64,
    invoice_no      STRING,
    customer_sk     INT64,
    return_ts       TIMESTAMP,
    refund_amount   NUMERIC(12,2),
    reason_code     STRING,
    status          STRING
)
CLUSTER BY return_id;

-- BigQuery DDL: retail.acid_customer_address_history
-- Source: Hive retail.acid_customer_address_history (acme-analytics/hive/13-additional-acid-tables.hql)
-- AC-14: ACID ORC table → standard BigQuery managed table, no ORC properties
-- Clustering: CLUSTERED BY (customer_sk) INTO 8 BUCKETS → CLUSTER BY customer_sk

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.acid_customer_address_history`
(
    history_id      INT64,
    customer_sk     INT64,
    address_line1   STRING,
    address_city    STRING,
    address_region  STRING,
    address_country STRING,
    address_postal  STRING,
    eff_from        TIMESTAMP,
    eff_to          TIMESTAMP,
    is_current      BOOL,
    change_reason   STRING
)
CLUSTER BY customer_sk;

-- BigQuery DDL: retail.acid_supplier_terms_history
-- Source: Hive retail.acid_supplier_terms_history (acme-analytics/hive/13-additional-acid-tables.hql)
-- AC-14: ACID ORC table → standard BigQuery managed table, DECIMAL→NUMERIC
-- Clustering: CLUSTERED BY (supplier_sk) INTO 4 BUCKETS → CLUSTER BY supplier_sk

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.acid_supplier_terms_history`
(
    history_id         INT64,
    supplier_sk        INT64,
    payment_terms_days INT64,
    discount_pct       NUMERIC(5,2),
    eff_from           TIMESTAMP,
    eff_to             TIMESTAMP,
    is_current         BOOL,
    changed_by         STRING
)
CLUSTER BY supplier_sk;

-- BigQuery DDL: retail.acid_loyalty_points_ledger
-- Source: Hive retail.acid_loyalty_points_ledger (acme-analytics/hive/13-additional-acid-tables.hql)
-- AC-14: ACID ORC table → standard BigQuery managed table
-- Clustering: CLUSTERED BY (member_id) INTO 8 BUCKETS → CLUSTER BY member_id

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.acid_loyalty_points_ledger`
(
    entry_id        INT64,
    member_id       STRING,
    points_delta    INT64,
    running_balance INT64,
    event_ts        TIMESTAMP,
    event_type      STRING,
    reference_id    STRING,
    expiry_ts       TIMESTAMP
)
CLUSTER BY member_id;

-- BigQuery DDL: retail.acid_inventory_adjustments_log
-- Source: Hive retail.acid_inventory_adjustments_log (acme-analytics/hive/13-additional-acid-tables.hql)
-- AC-14: ACID ORC table → standard BigQuery managed table
-- Clustering: CLUSTERED BY (adjustment_id) INTO 4 BUCKETS → CLUSTER BY adjustment_id

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.acid_inventory_adjustments_log`
(
    adjustment_id   INT64,
    warehouse_sk    INT64,
    sku             STRING,
    quantity_delta  INT64,
    reason_code     STRING,
    notes           STRING,
    adjusted_by     STRING,
    adjusted_at     TIMESTAMP,
    approved_by     STRING,
    approved_at     TIMESTAMP
)
CLUSTER BY adjustment_id;

-- BigQuery DDL: retail.bridge_product_attribute
-- Source: Hive retail.bridge_product_attribute (acme-analytics/hive/15-bridge-and-scd2.hql)
-- No partition (M:N bridge table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.bridge_product_attribute`
(
    product_sk     INT64,
    attribute_name STRING,
    attribute_value STRING,
    primary_value  BOOL,
    sort_order     INT64
);

-- BigQuery DDL: retail.bridge_product_supplier
-- Source: Hive retail.bridge_product_supplier (acme-analytics/hive/15-bridge-and-scd2.hql)
-- No partition (M:N bridge table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.bridge_product_supplier`
(
    product_sk         INT64,
    supplier_sk        INT64,
    primary_supplier   BOOL,
    supplier_sku       STRING,
    unit_cost          NUMERIC(12,4),
    lead_time_days     INT64,
    moq                INT64,
    valid_from         DATE,
    valid_to           DATE
);

-- BigQuery DDL: retail.bridge_customer_segment
-- Source: Hive retail.bridge_customer_segment (acme-analytics/hive/15-bridge-and-scd2.hql)
-- Partition: DATE snapshot_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.bridge_customer_segment`
(
    customer_sk     INT64,
    segment_id      STRING,
    segment_name    STRING,
    assigned_dt     DATE,
    expires_dt      DATE,
    confidence      NUMERIC(4,3),
    source          STRING,
    snapshot_date   DATE
)
PARTITION BY snapshot_date;

-- BigQuery DDL: retail.bridge_promo_eligibility
-- Source: Hive retail.bridge_promo_eligibility (acme-analytics/hive/15-bridge-and-scd2.hql)
-- Partition: DATE load_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.bridge_promo_eligibility`
(
    customer_sk    INT64,
    promo_sk       INT64,
    eligible       BOOL,
    reason         STRING,
    valid_from     DATE,
    valid_to       DATE,
    load_date      DATE
)
PARTITION BY load_date;

-- BigQuery DDL: retail.bridge_employee_role
-- Source: Hive retail.bridge_employee_role (acme-analytics/hive/15-bridge-and-scd2.hql)
-- No partition (M:N bridge table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.bridge_employee_role`
(
    employee_sk     INT64,
    role            STRING,
    primary_role    BOOL,
    eff_from        DATE,
    eff_to          DATE
);

-- BigQuery DDL: retail.dim_employee_history
-- Source: Hive retail.dim_employee_history (acme-analytics/hive/15-bridge-and-scd2.hql)
-- SCD-2 history dimension
-- Partition: INT eff_from_year → derived partition_year DATE (year-granularity)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_employee_history`
(
    history_id      INT64,
    employee_sk     INT64,
    role            STRING,
    department      STRING,
    home_store_sk   INT64,
    salary_band     STRING,
    eff_from        DATE,
    eff_to          DATE,
    is_current      BOOL,
    eff_from_year   INT64
);

-- BigQuery DDL: retail.dim_store_history
-- Source: Hive retail.dim_store_history (acme-analytics/hive/15-bridge-and-scd2.hql)
-- SCD-2 history dimension, no partition (small table)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.dim_store_history`
(
    history_id      INT64,
    store_sk        INT64,
    store_type      STRING,
    manager_employee_sk INT64,
    sq_ft           INT64,
    eff_from        DATE,
    eff_to          DATE,
    is_current      BOOL,
    change_reason   STRING
);

-- BigQuery DDL: retail.inventory_realtime_snapshot
-- Source: Hive retail.kudu_inventory_realtime (acme-analytics/hive/14-kudu-realtime.hql)
-- Category: kudu_snapshot (Kudu PRIMARY KEY/HASH → standard BigQuery table)
-- Kudu BIGINT timestamps → INT64 (epoch millis)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.inventory_realtime_snapshot`
(
    warehouse_id    STRING,
    sku             STRING,
    on_hand         INT64,
    allocated       INT64,
    available       INT64,
    last_updated_ts INT64
);

-- BigQuery DDL: retail.session_state_snapshot
-- Source: Hive retail.kudu_session_state (acme-analytics/hive/14-kudu-realtime.hql)
-- Category: kudu_snapshot (Kudu PRIMARY KEY/HASH → standard BigQuery table)
-- Kudu BIGINT timestamps → INT64 (epoch millis)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.session_state_snapshot`
(
    session_id      STRING,
    user_id         STRING,
    started_ts      INT64,
    last_event_ts   INT64,
    cart_value      NUMERIC(12,2),
    cart_items      INT64,
    current_screen  STRING,
    platform        STRING,
    geo_country     STRING
);

-- BigQuery DDL: retail.promo_eligibility_snapshot
-- Source: Hive retail.kudu_promo_eligibility (acme-analytics/hive/14-kudu-realtime.hql)
-- Category: kudu_snapshot (Kudu PRIMARY KEY/HASH → standard BigQuery table)
-- Kudu BIGINT timestamps → INT64 (epoch millis)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.promo_eligibility_snapshot`
(
    customer_id     STRING,
    promo_id        STRING,
    eligible        BOOL,
    eligibility_reason STRING,
    valid_from_ts   INT64,
    valid_to_ts     INT64,
    redeemed        BOOL
);

-- BigQuery DDL: retail.realtime_price_snapshot
-- Source: Hive retail.kudu_realtime_price (acme-analytics/hive/14-kudu-realtime.hql)
-- Category: kudu_snapshot (Kudu PRIMARY KEY/HASH → standard BigQuery table)
-- Kudu BIGINT timestamp → INT64 (epoch millis)

CREATE TABLE IF NOT EXISTS `acme-analytics.retail.realtime_price_snapshot`
(
    sku             STRING,
    store_id        STRING,
    price           NUMERIC(10,2),
    list_price      NUMERIC(10,2),
    cost            NUMERIC(10,2),
    margin_pct      NUMERIC(5,4),
    updated_ts      INT64,
    pricing_engine  STRING
);

-- BigQuery View: retail.vw_daily_sales_by_country
-- Source: Hive retail.vw_daily_sales_by_country (acme-analytics/hive/09-analytics-views.hql)
-- Translation: direct mapping — COALESCE/NULLIF are standard SQL, CTE + GROUP BY is direct.

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_daily_sales_by_country` AS
WITH daily AS (
  SELECT
    sale_date,
    country,
    COUNT(DISTINCT invoice_no)                  AS orders,
    SUM(line_total)                             AS revenue,
    SUM(quantity)                               AS units,
    COUNT(DISTINCT customer_sk)                 AS active_customers
  FROM `acme-analytics.retail.fact_sales`
  GROUP BY sale_date, country
)
SELECT
  d.sale_date,
  d.country,
  d.orders,
  d.revenue,
  d.units,
  d.active_customers,
  COALESCE(d.revenue / NULLIF(d.orders, 0), 0)  AS aov,
  COALESCE(d.units  / NULLIF(d.orders, 0), 0)   AS basket_size
FROM daily d;

-- BigQuery View: retail.vw_weekly_sales_with_running_totals
-- Source: Hive retail.vw_weekly_sales_with_running_totals (acme-analytics/hive/09-analytics-views.hql)
-- Translation: direct mapping — window functions (SUM OVER, AVG OVER, LAG) are standard SQL.

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_weekly_sales_with_running_totals` AS
WITH weekly AS (
  SELECT
    d.d_week_seq,
    d.d_year,
    SUM(f.line_total) AS wk_revenue,
    SUM(f.quantity)   AS wk_units
  FROM `acme-analytics.retail.fact_sales` f
  JOIN `acme-analytics.retail.dim_date` d ON d.d_date = f.sale_date
  GROUP BY d.d_week_seq, d.d_year
)
SELECT
  w.d_week_seq,
  w.d_year,
  w.wk_revenue,
  w.wk_units,
  SUM(w.wk_revenue) OVER (
    PARTITION BY w.d_year
    ORDER BY w.d_week_seq
  )                                                              AS ytd_revenue,
  AVG(w.wk_revenue) OVER (
    ORDER BY w.d_week_seq
    ROWS BETWEEN 12 PRECEDING AND CURRENT ROW
  )                                                              AS rolling_13wk_avg,
  LAG(w.wk_revenue, 52) OVER (ORDER BY w.d_week_seq)            AS same_week_last_year,
  w.wk_revenue - COALESCE(LAG(w.wk_revenue, 52) OVER (ORDER BY w.d_week_seq), 0)
                                                                 AS yoy_delta
FROM weekly w;

-- BigQuery View: retail.vw_customer_lifetime_value
-- Source: Hive retail.vw_customer_lifetime_value (acme-analytics/hive/09-analytics-views.hql)
-- Translation:
--   DATEDIFF(CURRENT_DATE(), last_order_date) → DATE_DIFF(CURRENT_DATE(), last_order_date, DAY)
--   CURRENT_DATE() → CURRENT_DATE() (same in BQ)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_customer_lifetime_value` AS
WITH per_customer AS (
  SELECT
    c.customer_sk,
    c.customer_id,
    c.country,
    MIN(f.sale_date)              AS first_order_date,
    MAX(f.sale_date)              AS last_order_date,
    COUNT(DISTINCT f.invoice_no)  AS orders,
    SUM(f.line_total)             AS lifetime_revenue
  FROM `acme-analytics.retail.dim_customer` c
  LEFT JOIN `acme-analytics.retail.fact_sales` f ON f.customer_sk = c.customer_sk
  GROUP BY c.customer_sk, c.customer_id, c.country
)
SELECT
  customer_sk,
  customer_id,
  country,
  first_order_date,
  last_order_date,
  orders,
  lifetime_revenue,
  DATE_DIFF(CURRENT_DATE(), last_order_date, DAY) AS recency_days,
  CASE
    WHEN orders = 0                                                    THEN 'never'
    WHEN DATE_DIFF(CURRENT_DATE(), last_order_date, DAY) <= 30        THEN 'active'
    WHEN DATE_DIFF(CURRENT_DATE(), last_order_date, DAY) <= 90        THEN 'warm'
    WHEN DATE_DIFF(CURRENT_DATE(), last_order_date, DAY) <= 365       THEN 'cold'
    ELSE 'churned'
  END                                              AS rfm_bucket
FROM per_customer;

-- BigQuery View: retail.vw_product_performance
-- Source: Hive retail.vw_product_performance (acme-analytics/hive/09-analytics-views.hql)
-- Translation: direct mapping — RANK/DENSE_RANK OVER are standard SQL.

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_product_performance` AS
WITH sold AS (
  SELECT
    p.product_sk,
    p.stock_code,
    p.description,
    f.country,
    SUM(f.line_total)                AS revenue,
    SUM(f.quantity)                  AS units,
    COUNT(DISTINCT f.invoice_no)     AS orders
  FROM `acme-analytics.retail.dim_product` p
  JOIN `acme-analytics.retail.fact_sales` f ON f.product_sk = p.product_sk
  GROUP BY p.product_sk, p.stock_code, p.description, f.country
),
ranked AS (
  SELECT
    s.*,
    RANK()       OVER (PARTITION BY s.country ORDER BY s.revenue DESC)  AS country_rank,
    DENSE_RANK() OVER (                       ORDER BY s.revenue DESC)  AS global_rank
  FROM sold s
)
SELECT * FROM ranked;

-- BigQuery View: retail.vw_monthly_cohort_retention
-- Source: Hive retail.vw_monthly_cohort_retention (acme-analytics/hive/09-analytics-views.hql)
-- Translation:
--   DATE_FORMAT(MIN(sale_date), 'yyyy-MM') → FORMAT_DATE('%Y-%m', MIN(sale_date))
--   MONTHS_BETWEEN(f.sale_date, to_date(concat(fo.cohort_month, '-01')))
--     → DATE_DIFF(f.sale_date, PARSE_DATE('%Y-%m-%d', CONCAT(fo.cohort_month, '-01')), MONTH)
--   CAST(months_since_first AS INT) → CAST(months_since_first AS INT64)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_monthly_cohort_retention` AS
WITH first_order AS (
  SELECT
    customer_sk,
    FORMAT_DATE('%Y-%m', MIN(sale_date)) AS cohort_month
  FROM `acme-analytics.retail.fact_sales`
  GROUP BY customer_sk
),
orders AS (
  SELECT
    f.customer_sk,
    fo.cohort_month,
    FORMAT_DATE('%Y-%m', f.sale_date)                                            AS order_month,
    DATE_DIFF(f.sale_date, PARSE_DATE('%Y-%m-%d', CONCAT(fo.cohort_month, '-01')), MONTH) AS months_since_first
  FROM `acme-analytics.retail.fact_sales` f
  JOIN first_order fo ON fo.customer_sk = f.customer_sk
)
SELECT
  cohort_month,
  CAST(months_since_first AS INT64)    AS months_since_first,
  COUNT(DISTINCT customer_sk)          AS active_customers
FROM orders
GROUP BY cohort_month, CAST(months_since_first AS INT64);

-- BigQuery View: retail.vw_otd_by_carrier_30d
-- Source: Hive retail.vw_otd_by_carrier_30d (acme-analytics/hive/16-additional-views.hql)
-- Translation:
--   shipped_ts + INTERVAL '48' HOUR → TIMESTAMP_ADD(shipped_ts, INTERVAL 48 HOUR)
--   unix_timestamp(delivered_ts) - unix_timestamp(shipped_ts)
--     → UNIX_SECONDS(delivered_ts) - UNIX_SECONDS(shipped_ts)
--   date_sub(current_date(), 30) → DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
--   shipped_ts >= date → CAST comparison (shipped_ts is TIMESTAMP, filter is DATE)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_otd_by_carrier_30d` AS
SELECT
    carrier,
    COUNT(*)                                                                     AS shipments,
    AVG(CASE WHEN delivered_ts <= TIMESTAMP_ADD(shipped_ts, INTERVAL 48 HOUR)
             THEN 1.0 ELSE 0.0 END)                                              AS otd_rate,
    AVG(UNIX_SECONDS(delivered_ts) - UNIX_SECONDS(shipped_ts)) / 3600.0           AS avg_transit_hours
FROM `acme-analytics.retail.fact_shipments`
WHERE shipped_ts >= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY))
GROUP BY carrier;

-- BigQuery View: retail.vw_session_to_order_attribution
-- Source: Hive retail.vw_session_to_order_attribution (acme-analytics/hive/09-analytics-views.hql)
-- Cross-project: raw.mobile_events → acme-analytics.raw.mobile_events
-- Translation:
--   s.event_ts + INTERVAL '1' DAY → TIMESTAMP_ADD(s.event_ts, INTERVAL 1 DAY)
--   s.context.referrer → s.context.referrer (STRUCT access is same in BQ)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_session_to_order_attribution` AS
SELECT
  s.user_id,
  s.event_ts                                AS session_ts,
  s.context.referrer                        AS referrer,
  f.invoice_no,
  f.invoice_ts                              AS order_ts,
  f.line_total
FROM `acme-analytics.raw.mobile_events` s
LEFT JOIN `acme-analytics.retail.dim_customer` dc ON dc.customer_id = s.user_id
LEFT JOIN `acme-analytics.retail.fact_sales` f
       ON  f.customer_sk = dc.customer_sk
       AND f.invoice_ts BETWEEN s.event_ts AND TIMESTAMP_ADD(s.event_ts, INTERVAL 1 DAY);

-- BigQuery View: retail.vw_active_member_panel
-- Source: Hive retail.vw_active_member_panel (acme-analytics/hive/16-additional-views.hql)
-- Trap T1: NDV() (Impala approx-distinct) → APPROX_COUNT_DISTINCT()
-- Translation:
--   NDV(member_id) → APPROX_COUNT_DISTINCT(member_id)
--   date_sub(current_date(), 30) → DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
-- Note: source view references `region` column on fact_loyalty_events. The source
--   Hive table does not have a `region` column — this view relies on a join or
--   implicit column. In BQ we join to dim_store via store_sk to get region.

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_active_member_panel` AS
SELECT
    s.region,
    APPROX_COUNT_DISTINCT(f.member_id)  AS approx_active_members,
    COUNT(DISTINCT f.member_id)         AS exact_active_members,
    SUM(f.points)                       AS total_points_redeemed
FROM `acme-analytics.retail.fact_loyalty_events` f
JOIN `acme-analytics.retail.dim_store` s ON s.store_sk = f.store_sk
WHERE f.event_type = 'REDEEM'
  AND f.event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
GROUP BY s.region;

-- BigQuery View: retail.vw_sales_rollup_by_region
-- Source: Hive retail.vw_sales_rollup_by_region (acme-analytics/hive/16-additional-views.hql)
-- Trap T2: WITH ROLLUP → GROUP BY ROLLUP(...)
-- Translation:
--   GROUP BY s.region, s.store_sk WITH ROLLUP → GROUP BY ROLLUP(s.region, s.store_sk)
--   GROUPING__ID → GROUPING(s.region) + GROUPING(s.store_sk) expression
--   date_sub(current_date(), 7) → DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_sales_rollup_by_region` AS
SELECT
    s.region,
    s.store_sk,
    SUM(f.line_total)              AS total_revenue,
    COUNT(*)                       AS line_count,
    GROUPING(s.region) * 2 + GROUPING(s.store_sk) AS grouping_level
FROM `acme-analytics.retail.fact_sales` f
JOIN `acme-analytics.retail.dim_store` s ON s.store_sk = f.customer_sk
WHERE f.sale_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)
GROUP BY ROLLUP(s.region, s.store_sk);

-- BigQuery View: retail.vw_category_hierarchy_recursive
-- Source: Hive retail.vw_category_hierarchy_recursive (acme-analytics/hive/16-additional-views.hql)
-- Trap T3: WITH RECURSIVE — BigQuery supports WITH RECURSIVE natively.
-- Translation: direct mapping with fully-qualified table references.

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_category_hierarchy_recursive` AS
WITH RECURSIVE cat_tree AS (
    SELECT
        category_id,
        name,
        parent_id,
        CAST(name AS STRING) AS path,
        0 AS depth
    FROM `acme-analytics.retail.dim_category`
    WHERE parent_id IS NULL OR parent_id = ''

    UNION ALL

    SELECT
        c.category_id,
        c.name,
        c.parent_id,
        CONCAT(t.path, ' > ', c.name) AS path,
        t.depth + 1                   AS depth
    FROM `acme-analytics.retail.dim_category` c
    JOIN cat_tree t ON c.parent_id = t.category_id
    WHERE t.depth < 8
)
SELECT * FROM cat_tree;

-- BigQuery View: retail.vw_panel_continuity_score
-- Source: Hive retail.vw_panel_continuity_score (acme-analytics/hive/16-additional-views.hql)
-- Trap T4: UDF inside JOIN ON clause.
-- Translation:
--   normalize_country(x) → `acme-analytics.retail.normalize_country`(x)
--   BigQuery UDF must be deployed before this view is created.
--   date_sub(current_date(), 90) → DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)

CREATE OR REPLACE VIEW `acme-analytics.retail.vw_panel_continuity_score` AS
SELECT
    f.customer_sk,
    COUNT(DISTINCT f.sale_date)         AS active_days,
    COUNT(DISTINCT f.product_sk)        AS distinct_products,
    SUM(f.line_total)                   AS total_spend
FROM `acme-analytics.retail.fact_sales` f
JOIN `acme-analytics.retail.dim_customer` c
  ON c.customer_sk = f.customer_sk
 AND `acme-analytics.retail.normalize_country`(c.country)
   = `acme-analytics.retail.normalize_country`(f.country)
WHERE f.sale_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)
GROUP BY f.customer_sk;


-- ============================================================================
-- REGIONAL_EU dataset — acme-analytics-eu.regional_eu
-- ============================================================================

-- BigQuery DDL: regional_eu.dim_currency_eu
-- Source: Hive regional.dim_currency_eu (acme-edge/hive/regional-additional-tables.hql)
-- No partition (small dimension table)
-- EU location: acme-analytics-eu.regional_eu

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.dim_currency_eu`
(
    currency_code   STRING,
    currency_name   STRING,
    minor_unit      INT64,
    symbol          STRING,
    eurozone        BOOL
);

-- BigQuery DDL: regional_eu.dim_product_eu_catalog
-- Source: Hive regional.dim_product_eu_catalog (acme-edge/hive/regional-additional-tables.hql)
-- ARRAY<STRING> eu_compliance_flags preserved
-- No partition (small dimension table)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.dim_product_eu_catalog`
(
    sku             STRING,
    eu_sku          STRING,
    name            STRING,
    description_de  STRING,
    description_fr  STRING,
    description_it  STRING,
    description_es  STRING,
    vat_pct         NUMERIC(5,4),
    eu_compliance_flags ARRAY<STRING>
);

-- BigQuery DDL: regional_eu.dim_gdpr_consent
-- Source: Hive regional.dim_gdpr_consent (acme-edge/hive/regional-additional-tables.hql)
-- AC-12: granted BOOL, consent_date DATE partition key, EU location
-- Partition: DATE consent_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.dim_gdpr_consent`
(
    consent_id      STRING,
    customer_id     STRING,
    consent_type    STRING,
    granted         BOOL,
    granted_ts      TIMESTAMP,
    withdrawn_ts    TIMESTAMP,
    source          STRING,
    legal_basis     STRING,
    expiry_ts       TIMESTAMP,
    consent_date    DATE
)
PARTITION BY consent_date;

-- BigQuery DDL: regional_eu.dim_locale_eu
-- Source: Hive regional.dim_locale_eu (acme-edge/hive/regional-additional-tables.hql)
-- No partition (small dimension table)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.dim_locale_eu`
(
    locale_code     STRING,
    country_iso2    STRING,
    language_iso2   STRING,
    timezone        STRING,
    currency_code   STRING,
    decimal_sep     STRING,
    date_format     STRING
);

-- BigQuery DDL: regional_eu.dim_customer_snapshot
-- Source: Hive regional.dim_customer_snapshot (acme-edge/hive/regional-events.hql)
-- No partition (small Sqoop landing table)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.dim_customer_snapshot`
(
    customer_sk    INT64,
    customer_id    STRING,
    country        STRING,
    snapshot_date  DATE
);

-- BigQuery DDL: regional_eu.fact_orders_eu
-- Source: Hive regional.fact_orders_eu (acme-edge/hive/regional-additional-tables.hql)
-- AC-11: partition by DATE(order_year, order_month, 1), cluster by country_partition and customer_id,
--         vat_amount NUMERIC
-- Multi-col partition (order_year/order_month/country_partition) → generated partition_month DATE
-- Clustering: CLUSTERED BY (customer_id) INTO 16 BUCKETS → CLUSTER BY country_partition, customer_id

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.fact_orders_eu`
(
    order_id        STRING,
    customer_id     STRING,
    sku             STRING,
    quantity        INT64,
    unit_price      NUMERIC(10,2),
    line_total      NUMERIC(14,2),
    currency_code   STRING,
    vat_amount      NUMERIC(12,2),
    order_ts        TIMESTAMP,
    country_iso2    STRING,
    order_year      INT64,
    order_month     INT64,
    country_partition STRING,
    partition_month DATE
)
PARTITION BY partition_month
CLUSTER BY country_partition, customer_id;

-- BigQuery DDL: regional_eu.fact_returns_eu
-- Source: Hive regional.fact_returns_eu (acme-edge/hive/regional-additional-tables.hql)
-- Partition: DATE return_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.fact_returns_eu`
(
    return_id       INT64,
    order_id        STRING,
    customer_id     STRING,
    sku             STRING,
    return_ts       TIMESTAMP,
    refund_amount   NUMERIC(12,2),
    reason_code     STRING,
    country_iso2    STRING,
    return_date     DATE
)
PARTITION BY return_date;

-- BigQuery DDL: regional_eu.fact_shipments_eu
-- Source: Hive regional.fact_shipments_eu (acme-edge/hive/regional-additional-tables.hql)
-- Partition: DATE ship_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.fact_shipments_eu`
(
    shipment_id     STRING,
    order_id        STRING,
    customer_id     STRING,
    carrier         STRING,
    tracking_no     STRING,
    shipped_at      TIMESTAMP,
    delivered_at    TIMESTAMP,
    country_from    STRING,
    country_to      STRING,
    sla_hours       INT64,
    ship_date       DATE
)
PARTITION BY ship_date;

-- BigQuery DDL: regional_eu.fact_mobile_app_events
-- Source: Hive regional.fact_mobile_app_events (acme-edge/hive/regional-additional-tables.hql)
-- MAP<STRING,STRING> properties → JSON (AC-13)
-- STRUCT<platform:STRING, model:STRING, os_version:STRING> preserved
-- Partition: STRING event_date + STRING platform_partition → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.fact_mobile_app_events`
(
    event_id        STRING,
    session_id      STRING,
    user_id         STRING,
    event_type      STRING,
    event_ts        TIMESTAMP,
    screen          STRING,
    device          STRUCT<platform STRING, model STRING, os_version STRING>,
    properties      JSON,
    country_iso2    STRING,
    event_date      STRING,
    platform_partition STRING,
    partition_date  DATE
)
PARTITION BY partition_date;

-- BigQuery DDL: regional_eu.fact_eu_promotions
-- Source: Hive regional.fact_eu_promotions (acme-edge/hive/regional-additional-tables.hql)
-- Partition: DATE redemption_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.fact_eu_promotions`
(
    redemption_id   INT64,
    promo_code      STRING,
    customer_id     STRING,
    order_id        STRING,
    discount_amount NUMERIC(12,2),
    currency_code   STRING,
    redeemed_ts     TIMESTAMP,
    country_iso2    STRING,
    redemption_date DATE
)
PARTITION BY redemption_date;

-- BigQuery DDL: regional_eu.staging_orders_eu
-- Source: Hive regional.staging_orders_eu (acme-edge/hive/regional-additional-tables.hql)
-- Partition: DATE snapshot_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.staging_orders_eu`
(
    order_id        STRING,
    customer_id     STRING,
    sku             STRING,
    quantity        INT64,
    unit_price      NUMERIC(10,2),
    currency_code   STRING,
    order_ts        TIMESTAMP,
    op              STRING,
    snapshot_date   DATE
)
PARTITION BY snapshot_date;

-- BigQuery DDL: regional_eu.staging_customers_eu_cdc
-- Source: Hive regional.staging_customers_eu_cdc (acme-edge/hive/regional-additional-tables.hql)
-- Partition: DATE snapshot_date (direct passthrough)

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.staging_customers_eu_cdc`
(
    customer_id     STRING,
    email           STRING,
    first_name      STRING,
    last_name       STRING,
    country_iso2    STRING,
    addr_postal     STRING,
    consent_marketing BOOL,
    updated_ts      TIMESTAMP,
    op              STRING,
    snapshot_date   DATE
)
PARTITION BY snapshot_date;

-- BigQuery DDL: regional_eu.events_eu
-- Source: Hive regional.events_eu (acme-edge/hive/regional-events.hql)
-- AC-13 note: payload_json is STRING in source (not MAP), stays STRING
-- Partition: STRING event_date → derived partition_date DATE

CREATE TABLE IF NOT EXISTS `acme-analytics-eu.regional_eu.events_eu`
(
    event_id     STRING,
    event_ts     TIMESTAMP,
    user_id      STRING,
    event_type   STRING,
    country_iso2 STRING,
    payload_json STRING,
    event_date   STRING,
    partition_date DATE
)
PARTITION BY partition_date;

-- BigQuery View: regional_eu.v_eu_orders_with_consent
-- Source: Hive regional.v_eu_orders_with_consent (acme-edge/hive/regional-additional-tables.hql)
-- Translation: direct mapping — COALESCE, LEFT JOIN, IS NULL are standard SQL.
-- EU-only project references: all tables use acme-analytics-eu.regional_eu.

CREATE OR REPLACE VIEW `acme-analytics-eu.regional_eu.v_eu_orders_with_consent` AS
SELECT
    o.order_id,
    o.customer_id,
    o.country_iso2,
    o.line_total,
    o.currency_code,
    COALESCE(c.granted, FALSE)            AS marketing_consent,
    c.granted_ts                          AS consent_granted_ts
FROM `acme-analytics-eu.regional_eu.fact_orders_eu` o
LEFT JOIN `acme-analytics-eu.regional_eu.dim_gdpr_consent` c
       ON c.customer_id = o.customer_id
      AND c.consent_type = 'MARKETING'
      AND c.granted = TRUE
      AND (c.withdrawn_ts IS NULL OR c.withdrawn_ts > o.order_ts);

